### ISSUE TITLE
Clarification over velocity in human_callback

### ISSUE THREAD

**Issue by Nabil-Miri** [Sven-Schepp/SaRA#10]
Hello, thanks for this interesting research and for open sourcing your code. 

I have a question in the reachability_occupancy.cpp and reachability_occupancy_no_udp.cpp file. In the human callback, shouldn't the v take the velocities as inputs and not positions?

```
  void human_callback(reachable_occupancy::JointLocations data){
    this->joint_pos_ = {};
    this->joint_vel_ = {};
    this->t_brake = data.delta_t;
    for (int i = 0; i < data.positions.size(); i++) {
      reach_lib::Point p;
      p.x = data.positions[i].x;
      p.y = data.positions[i].y;
      p.z = data.positions[i].z;

      reach_lib::Point v;
      v.x = data.positions[i].x;
      v.y = data.positions[i].y;
      v.z = data.positions[i].z;

      this->joint_pos_.push_back(p);
      this->joint_vel_.push_back(v);
    }
  }
```

Thanks.

**Comment by Sven-Schepp** [comment]
Hi,

thank you for your interest in our project. Those data in v.(x/y/z) are not used since our system did not transmit velocities directly. They are estimated using forward differences instead ([udp_transiever.cpp](https://github.com/Sven-Schepp/SaRA/blob/main/reachable_occupancy/src/udp_transiever.cpp)):

```
// Velocity estimation using forward difference
  for (int i = 0; i < this->joint_pos_.size(); i++) {
    this->joint_vel_.push_back((joint_pos_[i] - pos_prev[i]));
    this->joint_vel_[i].x /= delta_t;
    this->joint_vel_[i].y /= delta_t;
    this->joint_vel_[i].z /= delta_t;

    geometry_msgs::Point v;
    v.x = this->joint_vel_[i].x;
    v.y = this->joint_vel_[i].y;
    v.z = this->joint_vel_[i].z;
    joint_velocities.push_back(v);
```

If you plan on using the ReachLib library in ROS, I strongly encourage writing a custom main-script that is tailored to your needs. The implementation in this repo is meant to serve as a blueprint for such a script. If your system is capable of actively transmitting velocity data and your message type is structured similarly to [ours](https://github.com/Sven-Schepp/SaRA/blob/main/reachable_occupancy/msg/JointLocations.msg), then, I suggest using the measured velocities directly: 

`v.x = data.velocities[i].x`.

**Comment by Nabil-Miri** [comment]
Oh ok now it is more clear. Thanks a lot for your quick reply.
Another question if possible. I didn't notice any where in the code where it stops the robot in the ROS implementation. So is it because as you said the script available is considered as a blueprint and not everything is present in it ? 
Thanks.

**Comment by Sven-Schepp** [comment]
In our experiments, the robot was not controlled by our ROS script but by an external MATLAB controller. We got the robot trajectory from controller using UDP. You can implement start and stop signals for the hardware in your ROS script if that is more convenient for you. Our blueprint scripts, however, do not presently support that functionality.

**Comment by Nabil-Miri** [comment]
Noted. That’s clear now. Thanks a lot for your quick reply.
Good luck with your future work.
